import type { MetadataRoute } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://chsrvyt.github.io";

/*
 * Required by `output: export`: metadata routes are generated by a handler,
 * so Next needs telling explicitly that the result is a file to write once at
 * build time rather than a response to compute per request.
 */
export const dynamic = "force-static";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
